### PR TITLE
include only pertinent files in npm package

### PR DESCRIPTION
**Pull request by MarkHerhold**
ignores test files, .eslintrc, etc

### CODE REVIEW

**Comment by assaf** [comment]
I added README.md so the documentation is always available when using the module, and published 1.0.2

**Comment by MarkHerhold** [comment]
@assaf npm automatically includes the README and LICENSE regardless of if it is in the `files` array. Just FYI.

Edit: See https://docs.npmjs.com/files/package.json#files

**Comment by assaf** [comment]
I a) didn't know that it does that, and b) not going to remember that it does that tomorrow. I'm going to go with explicit over "only apparent to people who memorized the entire NPM spec".

**Comment by MarkHerhold** [comment]
I wasn't recommending that you remove it, only rationale for me not
includeing it. And good point. :+1:

**Comment by assaf** [comment]
Sorry. Didn't mean to be rude.

Often PRs get referenced elsewhere, e.g this is a change that I plan to roll out to other projects I'm working on, so as matter of practice I try to capture as much detail as possible, even if it's post-merge. So this wasn't a comment on your contribution, which is great, but more of what I should be doing in the next project, and the project after ...

**Pull request merged**
